### ISSUE TITLE
Flow

### ISSUE THREAD

**Issue by janpanschab** [actum/gulp-dev-stack#110]
This is must! :-)
Any idea why we should’t use [flow](https://flowtype.org/)?

**Comment by vbulant** [comment]
Well the only downside is a learning curve for React newbies but still I think we should use it.

**Comment by janpanschab** [comment]
Not related to React but I got it. And it’s valid point. Let’s test it first on our side projects ;-)

**Comment by vbulant** [comment]
Agreed. Also there are some edge cases – eg. when you wanna enable hot reloading in redux, you need to work with `module.hot` and flow wants you to annotate that but afaik nobody knows how at the moment :)

So we should try and explore it first.

**Comment by kettanaito** [comment]
As far as I know Flow encourages you to use flow-typed libraries alongside it. I am sure this can be excluded/disabled within its config, yet at the other hand it seems like a potential issue-raiser (since our devstack is oriented for everyone), and disables a part of advantages as well.

In general, imho it would be good to keep it as plain as possible. So everybody can add technologies they like on each project. Strongly typed code becomes popular, and new technologies slowly erupt.

**Comment by kettanaito** [comment]
I think we can close this issue, can't we? @janpanschab @vbulant 

Strong typing *is* a must, but Flow is not the only option ;) Generally, it's not difficult to setup any type checking supersets.

**Comment by vbulant** [comment]
@kettanaito Yes, I don’t think it should be enforced by the devstack.

**Comment by kettanaito** [comment]
Closing? :) @janpanschab
