### ISSUE TITLE
Watch

### ISSUE THREAD

**Issue by janpanschab** [actum/gulp-dev-stack#5]
Try gulp-watch or este-watch. Default gulp.watch does not trigger new or deleted files.

**Comment by omladek** [comment]
In gulpfile.babel.js you have to escape the expression for subfolders like this (tested on yachcharter):

gulp.watch(`${lessPath}/\**\/\*.less`, ['less']);
gulp.watch(`${srcPath}/\**\/\*.swig`, ['swig']);

**Comment by vbulant** [comment]
So, the problem is that `gulp.watch` has problems with globs starting with `./`. And `gulp-watch` as well, apparently: https://github.com/floatdrop/gulp-watch/issues/1

So I added function that sanitizes globs before passing them to watch.
I think it is better than manually removing `./` from path contants.
